- .aws/task-definition.json
- .github/workflows/ci-cd-workflow.yml
- README.md
- build.gradle
- settings.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/connection/RevalidationConnectionApplication.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/config/SentryConfiguration.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/revalidation/connection/RevalidationConnectionApplicationTest.java
> chore: Update template values for new project

- .aws/task-definition.json
- README.md
- build.gradle
> Chore/setup Sonar and Sentry

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
> chore: add Swagger description for endpoints

- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ConnectionDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ConnectionHistoryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/GmcResponseCode.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/ConnectionRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
- add response message
- sort by requestTime desc
TISNEW-5793
> fix: update connection history endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/UpdateConnectionDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/UpdateConnectionResponseDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ConnectionRequestType.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/HideConnectionLog.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/HideConnectionRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/HideRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/GmcClientService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/GmcClientServiceTest.java
> feat: added hide connection action end point

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
> Feat: Hidden connection

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ConnectionRequestType.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/HideConnectionLog.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
> feat: add unhide connection endpoint

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ExceptionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/AddConnectionReasonCode.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/GmcResponseCode.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/RemoveConnectionReasonCode.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionService.java
> fix: more fix for sonar cloud code smells

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/connection/config/RabbitConfig.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ExceptionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ExceptionSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ExceptionView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/RabbitMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/ExceptionElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelper.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/StringConverter.java
- src/main/resources/application.yml
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelperTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchServiceTest.java
> handle exception queue with Elastic Search

- .aws/task-definition-prod.json
- .aws/task-definition.json
- src/main/resources/application.yml
> chore: add ES url as parameter in task definition

- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ExceptionSummaryDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
> fix: update field name for ExceptionSummaryDto that match with FE

- .aws/task-definition-prod.json
- .aws/task-definition.json
> chore: update task-definition for ES URL parameter name

- src/main/resources/application.yml
> chore: remove Conditions Evaluation Report

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ExceptionView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/ExceptionElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelper.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelperTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchServiceTest.java
to avoid null gmcReferenceumber error
<NO-TICKET>
> fix: change ID of ES index

- .aws/task-definition-prod.json
- .aws/task-definition.json
> chore: add aws logs back

- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/DoctorsForDB.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/RecommendationStatus.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/UnderNotice.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/RabbitMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/DoctorsForDBRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
> feat: get GMC doctors data from mongoDb when TIS event triggered

- build.gradle
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/MasterDoctorView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/RabbitMessageListener.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelper.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/MasterElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/message/RabbitMessageListenerTest.java
to avoid ES index max_result_window excess error
> fix: Use Scroll API instead of findAll

- .aws/task-definition-prod.json
- .aws/task-definition.json
Swap the DB secrets with new Terraformed parameters.
TIS21-1517
> chore: Use terraformed params for db secrets

- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/RabbitMessageListener.java
> fix: use log.debug for message receive when event trigger update

- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/DisconnectedElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchService.java
> fix: add try catch for ES operations

- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/ConnectionMessageReceiver.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/ConnectionMessageReceiverTest.java
> fix: get gmc data from masterindex instead of recommendation 

- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/ConnectionInfoDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ConnectedView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/DisconnectedView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ExceptionView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/MasterDoctorView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelper.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/message/listener/RabbitMessageListenerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/GmcDoctorMessageReceiverTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/message/receiver/SyncMessageReceiverTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/DisconnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticSearchIndexUpdateHelperTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionUpdateExceptionElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/MasterElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/UpdateConnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/UpdateDisconnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/UpdateExceptionElasticSearchServiceTest.java
> feat: add ExceptionReason field and exception logic for GMC failure case

- .github/workflows/ci-cd-workflow.yml
- .github/workflows/pr-analysis.yml
> chore: rename master to main

- src/main/java/uk/nhs/hee/tis/revalidation/connection/config/RabbitConfig.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/listener/RabbitMessageListener.java
- src/main/resources/application.yml
TIS21-2669: Filter Recommendations with ES - Rebuild ES Job
> chore: update get master queue name

- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/DiscrepanciesView.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/mapper/ConnectionInfoMapper.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/DiscrepanciesElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/mapper/ConnectionInfoMapperTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionUpdateExceptionElasticSearchServiceTest.java
TIS21-4360: Revalidation Connections: GET Discrepancies where TISDBC != GMCDBC
> feat: GET exceptions using discrepancies alias

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
Discrepancies list uses "/exception" API.
TIS21-4554
> fix: use lower case search query for discrepancies

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/DiscrepanciesElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelper.java
- src/main/resources/esJson/discrepancies/findall.json
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ElasticsearchQueryHelperTest.java
TIS21-4633: Reval Connections MVP: Restrict Discrepancies list by Designated Body
> feat: restrict discrepancies list to admin's DBCs matching in TCS or GMC

- src/main/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionController.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/CurrentConnectionElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/DiscrepanciesElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchService.java
- src/main/resources/esJson/currentConnections/findall.json
- src/main/resources/esJson/discrepancies/findall.json
- src/test/java/uk/nhs/hee/tis/revalidation/connection/controller/ConnectionControllerTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectedElasticSearchServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/DiscrepanciesElasticSearchServiceTest.java
TIS21-4639: Add programme name filter to current connections and discrepancies
> feat: filter by programme name

- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/CurrentConnectionElasticSearchRepository.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/repository/DiscrepanciesElasticSearchRepository.java
- src/main/resources/esJson/currentConnections/findall.json
- src/main/resources/esJson/discrepancies/findall.json
> fix: must_not query syntax fix

- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/GmcConnectionResponseDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/message/ConnectionMessage.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/GmcClientService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/GmcClientServiceTest.java
TIS21-5015: Update submission date using gmc tryadddoctor response data when connecting a doctor
> fix: update submission date when adding a new connection

- src/main/java/uk/nhs/hee/tis/revalidation/connection/dto/UpdateConnectionDto.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/entity/ExceptionLog.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionService.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionServiceTest.java
- src/test/java/uk/nhs/hee/tis/revalidation/connection/service/ExceptionServiceTest.java
TIS21-5176 Pass admin to endpoint from FE when updating a connection - single or bulk
> feat: save admin name when updating a connection

- src/main/java/uk/nhs/hee/tis/revalidation/connection/service/ConnectionService.java
> fix: helpful error message for bulk connection failures

- .aws/task-definition-template.json
- src/main/resources/application.yml
TIS21-6612: Upgrade Reval DocDB Cluster
> chore: use parameter store value for mongo connection string parameters
